version: "3"
services:
  web:
    build:
      context: ./frontend-service
      dockerfile: ./frontend-service.dockerfile
    ports:
      - "3010:80"
  logger-service:
    build:
      context: ./logger-service
      dockerfile: ./logger-service.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
